services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: krlx26/shopsmart-server:v1
    container_name: shopsmart-server
    ports:
      - "5001:5000" # Avoid AirPlay conflict on 5000
    environment:
      - PORT=5000
      - DATABASE_URL=file:./dev.db
    networks:
      - shopsmart-net

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: krlx26/shopsmart-client:v1
    container_name: shopsmart-client
    ports:
      - "5173:5173"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
    depends_on:
      - server
    networks:
      - shopsmart-net

networks:
  shopsmart-net:
    driver: bridge
